title: Coleman Barkley # your name (or website title) here
logo: "/images/Orientation Headshot 2.jpg?raw=false" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Future Data Scientist
  <br>
  Image Analyics Engineer at BNSF Railway
  <br><br>
  Currently persuing an MS in Advanced Data Analytics
  <br>
  Target Graduation: Aug 2020
  <br>
  <a href="https://www.linkedin.com/in/colemanbarkley/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
